//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SafeWeb.PurchaseApprover.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ValidationResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SafeWeb.PurchaseApprover.Resources.ValidationResources", typeof(ValidationResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O valor deve ser maior que R$ {0}..
        /// </summary>
        public static string Amount_GreatherThan {
            get {
                return ResourceManager.GetString("Amount_GreatherThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A data de nascimento deve ser informada..
        /// </summary>
        public static string BirthDate_Empty {
            get {
                return ResourceManager.GetString("BirthDate_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A categoria informada é inválida..
        /// </summary>
        public static string Category_Invalid {
            get {
                return ResourceManager.GetString("Category_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A categoria informada não foi encontrada..
        /// </summary>
        public static string Category_NotFound {
            get {
                return ResourceManager.GetString("Category_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A data deve ser informada..
        /// </summary>
        public static string Date_Empty {
            get {
                return ResourceManager.GetString("Date_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A descrição deve ser informada..
        /// </summary>
        public static string Description_Empty {
            get {
                return ResourceManager.GetString("Description_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A descrição deve possuir entre {0} e {1} caracteres..
        /// </summary>
        public static string Description_InvalidLength {
            get {
                return ResourceManager.GetString("Description_InvalidLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O número de documento informado é inválido..
        /// </summary>
        public static string DocumentNumber_Invalid {
            get {
                return ResourceManager.GetString("DocumentNumber_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O e-mail deve ser informado..
        /// </summary>
        public static string Email_Empty {
            get {
                return ResourceManager.GetString("Email_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O e-mail informado é inválido..
        /// </summary>
        public static string Email_Invalid {
            get {
                return ResourceManager.GetString("Email_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome deve ser informado..
        /// </summary>
        public static string Name_Empty {
            get {
                return ResourceManager.GetString("Name_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome deve possuir entre {0} e {1} caracteres..
        /// </summary>
        public static string Name_InvalidLength {
            get {
                return ResourceManager.GetString("Name_InvalidLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O telefone deve ser informado..
        /// </summary>
        public static string Phone_Empty {
            get {
                return ResourceManager.GetString("Phone_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O telefone deve possuir entre {0} e {1} caracteres..
        /// </summary>
        public static string Phone_Invalid {
            get {
                return ResourceManager.GetString("Phone_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esta proposta não pode ser modificada, pois já foi aprovada..
        /// </summary>
        public static string Proposal_CannotBeModified_Approved {
            get {
                return ResourceManager.GetString("Proposal_CannotBeModified_Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esta proposta não pode ser modificada, pois já expirou após {0}h da criação..
        /// </summary>
        public static string Proposal_CannotBeModified_Expired {
            get {
                return ResourceManager.GetString("Proposal_CannotBeModified_Expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A proposta informada não foi encontrada..
        /// </summary>
        public static string Proposal_NotFound {
            get {
                return ResourceManager.GetString("Proposal_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O fornecedor informado é inválido..
        /// </summary>
        public static string Supplier_Invalid {
            get {
                return ResourceManager.GetString("Supplier_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O fornecedor informado não foi encontrado..
        /// </summary>
        public static string Supplier_NotFound {
            get {
                return ResourceManager.GetString("Supplier_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O usuário administrativo principal não pode ser alterado através do painel administrativo..
        /// </summary>
        public static string User_CannotModifyMainUser {
            get {
                return ResourceManager.GetString("User_CannotModifyMainUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O usuário informado não foi encontrado..
        /// </summary>
        public static string User_NotFound {
            get {
                return ResourceManager.GetString("User_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O perfil de usuário deve ser informado..
        /// </summary>
        public static string User_UserProfile_Null {
            get {
                return ResourceManager.GetString("User_UserProfile_Null", resourceCulture);
            }
        }
    }
}
